//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MESConsoleClient.MESServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MESServer")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MESServiceReference.IMESService")]
    public interface IMESService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetData", ReplyAction="http://tempuri.org/IMESService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetData", ReplyAction="http://tempuri.org/IMESService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMESService/GetDataUsingDataContractResponse")]
        MESConsoleClient.MESServiceReference.CompositeType GetDataUsingDataContract(MESConsoleClient.MESServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMESService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MESConsoleClient.MESServiceReference.CompositeType> GetDataUsingDataContractAsync(MESConsoleClient.MESServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetDiff", ReplyAction="http://tempuri.org/IMESService/GetDiffResponse")]
        int GetDiff(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetDiff", ReplyAction="http://tempuri.org/IMESService/GetDiffResponse")]
        System.Threading.Tasks.Task<int> GetDiffAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetDepartments", ReplyAction="http://tempuri.org/IMESService/GetDepartmentsResponse")]
        MESModel.Department[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/GetDepartments", ReplyAction="http://tempuri.org/IMESService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<MESModel.Department[]> GetDepartmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/InitDb", ReplyAction="http://tempuri.org/IMESService/InitDbResponse")]
        string InitDb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMESService/InitDb", ReplyAction="http://tempuri.org/IMESService/InitDbResponse")]
        System.Threading.Tasks.Task<string> InitDbAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMESServiceChannel : MESConsoleClient.MESServiceReference.IMESService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MESServiceClient : System.ServiceModel.ClientBase<MESConsoleClient.MESServiceReference.IMESService>, MESConsoleClient.MESServiceReference.IMESService {
        
        public MESServiceClient() {
        }
        
        public MESServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MESServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MESServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MESServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MESConsoleClient.MESServiceReference.CompositeType GetDataUsingDataContract(MESConsoleClient.MESServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MESConsoleClient.MESServiceReference.CompositeType> GetDataUsingDataContractAsync(MESConsoleClient.MESServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int GetDiff(int a, int b) {
            return base.Channel.GetDiff(a, b);
        }
        
        public System.Threading.Tasks.Task<int> GetDiffAsync(int a, int b) {
            return base.Channel.GetDiffAsync(a, b);
        }
        
        public MESModel.Department[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<MESModel.Department[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
        
        public string InitDb() {
            return base.Channel.InitDb();
        }
        
        public System.Threading.Tasks.Task<string> InitDbAsync() {
            return base.Channel.InitDbAsync();
        }
    }
}
